language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - python3 setup.py install
  - pip install codecov
  - pip install stdeb
  - sudo apt-get install -y debhelper python3-all python3-setuptools
# command to run tests
script:
  - python3 setup.py install
  - python3 setup.py --command-packages=stdeb.command bdist_deb
  - nosetests --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
